"use client";

import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";

import { TypographyH2, TypographyP } from "@/components/ui/typography";

function Index() {
  const router = useRouter();

  return (
    <>
      <div>
        <TypographyH2>General</TypographyH2>
        <ul className="my-6 ml-6 list-disc [&>li]:mt-2 flex flex-col gap-2">
          <li>Every lamp has unique lamp code</li>
          <li>
            You can generate lamp code via{" "}
            <Link
              href="/lamp/connect"
              className={buttonVariants({ variant: "link" })}
            >
              connect page
            </Link>{" "}
            and set it to your lamp
          </li>
          <li>
            After generating lamp code will be automatically saved in your
            browser
          </li>
          <li>
            If you want to add lamp to other browser you can do it on{" "}
            <Link
              href="/lamp/add"
              className={buttonVariants({ variant: "link" })}
            >
              add page
            </Link>{" "}
          </li>
        </ul>
      </div>
      <div>
        <TypographyH2>Security</TypographyH2>
        <TypographyP>
          Lamp code is unique for every lamp and is generated by the server.
          It&apos;s not possible to generate the same code twice. Code is
          generated randomly and is not predictable.
        </TypographyP>
        <TypographyP>
          Lamp code is saved in your browser and is not shared with the server.
          It&apos;s used only to connect your lamp to the server.
        </TypographyP>
      </div>
      <div>
        <TypographyH2>Privacy</TypographyH2>
        <TypographyP>
          Lamp code is not shared with other users. It&apos;s unique for every
          lamp and is generated randomly.
        </TypographyP>
      </div>
      <div>
        <TypographyH2>Authors</TypographyH2>
        <TypographyP>
          Course project for the subject of embedded systems carried out by{" "}
          <Link
            href="https://github.com/azizko1337"
            target="_blank"
            className={buttonVariants({ variant: "link" })}
          >
            Antoni Załupka
          </Link>{" "}
          and{" "}
          <Link
            href="#"
            target="_blank"
            className={buttonVariants({ variant: "link" })}
          >
            Bartłomiej Marzec
          </Link>
        </TypographyP>
      </div>
    </>
  );
}

export default Index;
