"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { TypographyLarge, TypographyH3 } from "@/components/ui/typography";
import { buttonVariants } from "@/components/ui/button";

import socket from "@/lib/socket";
import saveLampCode from "@/lib/saveLampCode";
import copyToClipboard from "@/lib/copyToClipboard";

function ConnectLamp() {
  const router = useRouter();

  const [lampCode, setLampCode] = useState("");
  const [feedback, setFeedback] = useState("");

  useEffect(() => {
    socket.on("generateLampCode", async ({ lampCode }) => {
      setLampCode(lampCode);
      saveLampCode(lampCode);

      try {
        await copyToClipboard("I'm going to the clipboard !");
        setFeedback("Code has been copied to clipboard!");
      } catch (error) {
        setFeedback(
          "Code couldn't be copied to clipboard. Please copy it manually."
        );
      }
    });

    return () => {
      socket.off("generateLampCode");
    };
  }, [router, lampCode]);

  const connectLamp = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    socket.emit("generateLampCode", "");
  };

  return (
    <>
      <div></div>
      <div>
        <TypographyH3>Steps to connect your lamp:</TypographyH3>
        <ol className="my-6 ml-6 list-decimal [&>li]:mt-2">
          <li>Connect your lamp to power</li>
          <li>
            Take your phone and connect to your lamp&apos;s WiFi (name: Lamp)
          </li>
          <li>Go to 10.0.0.1 in your browser</li>
          <li>
            Select your home WiFi network, type password and code generated by
            the button below. Code is automatically copied to your clipboard
          </li>
        </ol>
      </div>
      <div className="flex flex-col gap-2">
        <Button onClick={connectLamp}>Generate lamp code</Button>
        <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
          {lampCode}
        </div>
        <TypographyLarge>{feedback}</TypographyLarge>
      </div>
      {lampCode && (
        <div>
          <TypographyH3>Further steps:</TypographyH3>
          <ol className="my-6 ml-6 list-decimal [&>li]:mt-2">
            <li>
              If your lamp have connected successfully, yellow light on it will
              turn off
            </li>
            <li>
              Now you can go to{" "}
              <Link
                href="/lamp/list"
                className={buttonVariants({ variant: "link" })}
              >
                your lamps
              </Link>{" "}
              and manage them!
            </li>
          </ol>
        </div>
      )}
    </>
  );
}

export default ConnectLamp;
